language: python
python:
  - "3.6"
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cairo; fi
install:
  - pip install flake8==3.3.0
before_script: "flake8 zeppelin tests"
script: "python setup.py test"
